
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>AnimLib</AssemblyName>
    <LangVersion>preview</LangVersion>
	<Description>Terraria library mod for enhanced animations and ability management.</Description>
	<RepositoryUrl>https://github.com/Ilemni/AnimLib</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
	<Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AsepriteDotNet" Version="1.9.0" />
    <PackageReference Include="JetBrains.Annotations" Version="2021.1.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="AsepriteDotNet">
      <HintPath>lib\AsepriteDotNet.dll</HintPath>
    </Reference>
    <Reference Include="MrPlagueRaces">
      <HintPath>..\ModAssemblies\MrPlagueRaces_v0.3.8.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>